//--------------------------------------------------
// Enumerations of User Timer Events
//--------------------------------------------------
    _USER_TIMER_EVENT_KEY_REPEAT_ENABLE,
    _USER_TIMER_EVENT_KEY_SCAN_READY,
    _USER_TIMER_EVENT_OSD_DISABLE_OSD_LOGO,
    _USER_TIMER_EVENT_OSD_SHOW_NO_CABLE,
    _USER_TIMER_EVENT_OSD_SHOW_NO_SIGNAL,
    _USER_TIMER_EVENT_OSD_SHOW_POWER_SAVING,
    _USER_TIMER_EVENT_OSD_WAIT_POWER_SAVING,
    _USER_TIMER_EVENT_GO_TO_POWER_SAVING,
    _USER_TIMER_EVENT_OSD_DISABLE,
    _USER_TIMER_EVENT_OSD_DISABLE_120s,
    _USER_TIMER_EVENT_PANEL_BACKLIGHT_ON,
    _USER_TIMER_EVENT_PANEL_POWER_OFF,
    _USER_TIMER_EVENT_DO_AUTO_COLOR,
    _USER_TIMER_EVENT_PANEL_USED_TIMER,

#if(_HIGHLIGHT_WINDOW_SUPPORT == _ON)
    _USER_TIMER_EVENT_HLWIN_TYPE5_MOVE,
#endif																	

#if(_FREEZE_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_DISABLE_FREEZE_MSG,
#endif

#if(_LD_HDR10_BOOST_SUPPORT == _ON)
     _USER_TIMER_EVENT_HDR_BOOST,
     _USER_TIMER_EVENT_HDR_COOL,
#endif

	_USER_TIMER_EVENT_LED_MODE_FLICKER,
	_USER_TIMER_EVENT_AUTO_POWER_DOWN,
	
	_USER_TIMER_EVENT_AUTO_POWER_DOWN_MSG,
	_USER_TIMER_EVENT_BUININ_MSG,
#if(_DCR_SUPPORT == _ON)
	 _USER_TIMER_EVENT_DCR_CAL_TIME,
	 _USER_TIMER_EVENT_DCR_TUNE_PWM_TIMER,
	
#endif
	_USER_TIMER_EVENT_DO_POWER_DOWN,
	_USER_TIMER_EVENT_MPRT,
	
	_USER_TIMER_EVENT_LOCK_OSD,	//�˵���
	_USER_TIMER_EVENT_LOCK_POWER_KEY,	//��Դ��

	_USER_REAL_TIME_REFRESH_RATE,	//ʵʱ��ϸˢ����	
	
	_USER_TIMER_EVENT_FACTORY,

#if((_FREESYNC_SUPPORT == _ON)&&(_OSD_VFREQ_CHANGE == _ON))
       _USER_TIMER_EVENT_OSD_SHOW_DRR_VFREQ,
#endif
#if(_DEF_DDCCI_EDID_TOOL)
	_USER_TIMER_EVENT_BURN_IN_DDCTOOL,
#endif

