#include "SysInclude.h"
extern void BANK0(char *str, ...);
extern void BANK1(char *str, ...);
extern void BANK2(char *str, ...);
extern void BANK3(char *str, ...);
extern void BANK4(char *str, ...);
extern void BANK5(char *str, ...);
extern void BANK6(char *str, ...);
extern void BANK7(char *str, ...);
extern void BANK8(char *str, ...);
extern void BANK9(char *str, ...);
extern void BANK10(char *str, ...);
extern void BANK11(char *str, ...);
extern void BANK12(char *str, ...);
extern void BANK13(char *str, ...);
extern void BANK14(char *str, ...);
extern void BANK15(char *str, ...);
extern void BANK16(char *str, ...);
extern void BANK17(char *str, ...);
extern void BANK18(char *str, ...);
extern void BANK19(char *str, ...);
extern void BANK20(char *str, ...);
extern void BANK21(char *str, ...);
extern void BANK22(char *str, ...);
extern void BANK23(char *str, ...);
extern void BANK24(char *str, ...);
extern void BANK25(char *str, ...);
extern void BANK26(char *str, ...);
extern void BANK27(char *str, ...);
extern void BANK28(char *str, ...);
extern void BANK29(char *str, ...);
extern void BANK30(char *str, ...);
extern void BANK31(char *str, ...);
extern void BANKX(int bank, char *str, ...);
extern void BANK_LIMIT(int value);
extern void COMMON(char *str, ...);
extern void COMM_SEG(char *str);
extern void FUNC(char *str, int addr);
extern void OVERLAY(char *str);
extern void TABLE(char *str, int addr);
extern void WRITE_BANK_END(int bank, int addr);
extern void WRITE_COMMON_END(int bank, int addr);
void test_code(void) {
#if(_DUAL_BANK_SUPPORT == _ON)
#if((_DUAL_BANK_TYPE != _DUAL_BANK_FLASH_PARTITION) && (_DUAL_BANK_TYPE != _DUAL_BANK_FLASH_PARTITION_USER_FLAG_MODE))
    BANK0("SYSMAIN");
    FUNC("?PR?SYSMAINSTARTUSERCODE?SYSMAIN",0x4000);
    BANK_LIMIT(_DUAL_BANK_USER_FW_CODE_SIZE);
#else
#if(_DUAL_BANK_FLASH_PARTITION_BOOT_USER_SEL == _DUAL_BANK_FLASH_PARTITION_USER)
    BANK0("SYSMAIN");
    FUNC("?PR?SYSMAINSTARTUSERCODE?SYSMAIN",0x4000);
    BANK_LIMIT(_DUAL_BANK_USER_FW_CODE_SIZE);
#else
    BANK0("USERCOMMONDUALBANKPROCESS");
    FUNC("?PR?USERCOMMONDUALBANKPROCESSRUNUSERCODE?USERCOMMONDUALBANKPROCESS",0x4000);
    BANK_LIMIT(_DUAL_BANK_USER_FW_START_BANK);
#endif
#endif
#endif
    COMM_SEG("?PR?SCALERMCUMEMORYZEROINIT?RL6463_SERIES_MCU");
#if((_DUAL_BANK_SUPPORT == _OFF) || ((_DUAL_BANK_FLASH_PARTITION_SUPPORT == _ON) && (_DUAL_BANK_FLASH_PARTITION_BOOT_USER_SEL != _DUAL_BANK_FLASH_PARTITION_USER)))
    BANK0("RL6463_SERIES_PC99EDID");
#if((_A0_EMBEDDED_DDCRAM_LOCATION == _EDID_TABLE_LOCATION_PC99) || (_D0_EMBEDDED_DDCRAM_LOCATION == _EDID_TABLE_LOCATION_PC99) || (_D1_EMBEDDED_DDCRAM_LOCATION == _EDID_TABLE_LOCATION_PC99))
    TABLE("?CO?RL6463_SERIES_PC99EDID",0xF000);
#else
    TABLE("?CO?RL6463_SERIES_PC99EDID",0xFD70);
#endif
    OVERLAY("* ! ?CO?RL6463_SERIES_PC99EDID");
#endif
#if(_DUAL_BANK_FP_USER_FLAG_TABLE_SUPPORT == _ON)
    BANKX(_DUAL_BANK_USER_I_FLAG_LOCATE_BANK,"USERCOMMONDUALBANKUSERTABLE");
    TABLE("?CO?USERCOMMONDUALBANKUSERTABLE",_DUAL_BANK_FLASH_PARTITION_USER_FLAG_ADDRESS);
    OVERLAY("* ! ?CO?USERCOMMONDUALBANKUSERTABLE");
#endif
#if(_DUAL_BANK_USER_DATA_TABLE_SUPPORT == _ON)
    BANK_LIMIT(_DUAL_BANK_USER_FW_CODE_SIZE);
    BANKX(_DUAL_BANK_USER_I_FLAG_LOCATE_BANK,"USERCOMMONDUALBANKUSERTABLE");
    TABLE("?CO?USERCOMMONDUALBANKUSERTABLE",_DUAL_BANK_USER_DATA_SECTOR_ADDRESS);
    OVERLAY("* ! ?CO?USERCOMMONDUALBANKUSERTABLE");
#endif
#if(_DUAL_BANK_USER_II_DATA_TABLE_SUPPORT == _ON)
    BANKX(_DUAL_BANK_USER_II_FLAG_LOCATE_BANK,"USERCOMMONDUALBANKUSERTABLEII");
    TABLE("?CO?USERCOMMONDUALBANKUSERTABLEII",_DUAL_BANK_USER_DATA_SECTOR_ADDRESS);
    OVERLAY("* ! ?CO?USERCOMMONDUALBANKUSERTABLEII");
#endif
#if(_CUSTOMER_FW_VERSION_SUPPORT == _ON)
    BANKX(_CUSTOMER_FW_VERSION_LOCATE_BANK,"SCALERCOMMONFWINFO");
    TABLE("?CO?SCALERCOMMONFWINFO",_CUSTOMER_FW_VERSION_LOCATE_ADDRESS);
    OVERLAY("* ! ?CO?SCALERCOMMONFWINFO");
#endif
    COMM_SEG("?PR?SYSTIMERINTPROC0?SYSTIMER");
    COMM_SEG("?PR?SYSTIMERINTPROC1?SYSTIMER");
    COMM_SEG("?PR?SYSTIMERINTPROC2?SYSTIMER");
    COMM_SEG("?PR?SYSTIMERWDINTPROC?SYSTIMER");
#if(_SYSTEM_EEPROM_EMULATION_SUPPORT == _OFF)
    COMM_SEG("?PR?_USERCOMMONEEPROMWRITE?USERCOMMONNVRAMSYSTEM");
    COMM_SEG("?PR?_USERCOMMONEEPROMIICWRITE?USERCOMMONNVRAMSYSTEM");
#endif
#if((_DP_TYPE_C_PORT_CTRL_SUPPORT == _ON) && (_PORT_CONTROLLER_RTS_SMBUS_SUPPORT == _ON))
    COMM_SEG("?PR?_USERCOMMONTYPECCOMMUNICATIONWRITE?USERCOMMONTYPECCOMMUNICATION");
    COMM_SEG("?PR?_USERCOMMONTYPECCOMMUNICATIONSMBWRITE?USERCOMMONTYPECCOMMUNICATION");
#endif
#if(_HW_IIC_SUPPORT == _ON)
    COMM_SEG("?PR?_SCALERMCUHWIICWRITE?SCALERCOMMONMCU");
#endif
#if(_SW_IIC_SUPPORT == _ON)
    COMM_SEG("?PR?_SCALERMCUIICWRITE?SCALERCOMMONMCU");
#endif
#if(_PANEL_EXIST_MULTIPANEL == _ON)
    COMMON("SCALERDDOMAIN");
#endif
#if(_SPI_SUPPORT == _ON)
    COMM_SEG("?PR?SCALERSPIDATA?SCALERCOMMONSPI");
    COMM_SEG("?PR?SCALERSPISPIDATACEFORCELOW?SCALERCOMMONSPI");
#endif
#if((_DP_SUPPORT == _ON) && (_DP_IRQ_HPD_MODE == _DP_IRQ_HPD_T2_MODE))
    COMM_SEG("?PR?SCALERSYNCDPHPDIRQASSERTTIMER2EVENTPROC_EXINT?SCALERCOMMONSYNC");
#endif
#if((_DP_SUPPORT == _ON) && (_DP_AUX_RX_DPCD_EXT_CAP_WILDCARD_SUPPORT == _ON))
    COMM_SEG("?PR?SCALERDPRXAUXTIMER2PREINTHANDLER_EXINT?SCALERDP_SEPTPHY");
#endif
#if(_ISP_FW_CHECK_PROJECT_ID_SUPPORT == _ON)
    BANKX(_ISP_FW_CHECK_PROJECT_ID_LOCATION_BANK,"SCALERCOMMONFWCHECK");
    TABLE("?CO?SCALERCOMMONFWCHECK",_ISP_FW_CHECK_PROJECT_ID_LOCATION_ADDRESS);
    OVERLAY("* ! ?CO?SCALERCOMMONFWCHECK");
#endif
#if((_DUAL_BANK_SUPPORT == _ON) && ((_DUAL_BANK_TYPE == _DUAL_BANK_DIFF_BANK) || (_DUAL_BANK_TYPE == _DUAL_BANK_COPY_BANK)))
#if((_FW_UPDATE_FOREGROUND_SUPPORT == _ON) &&(_FW_UPDATE_CHECK_TYPE == _FW_UPDATE_CHECK_RTK_RSA2048))
    BANKX(_DUAL_BANK_USER_FW_CODE_SIZE - 1,"USERCOMMONFWUPDATESIGNATURETABLE");
    TABLE("?CO?USERCOMMONFWUPDATESIGNATURETABLE",_FW_UPDATE_SIGN_INFO_SECTOR_ADDRESS);
    OVERLAY("* ! ?CO?USERCOMMONFWUPDATESIGNATURETABLE");
#endif
#if((_FW_UPDATE_FOREGROUND_SUPPORT == _ON) &&(_FW_UPDATE_CHECK_TYPE == _FW_UPDATE_CHECK_PASSWORD))
    BANKX(_FW_UPDATE_PASSWORD_BANK,"USERCOMMONFWUPDATEPASSWORD");
    TABLE("?CO?USERCOMMONFWUPDATEPASSWORD",_FW_UPDATE_PASSWORD_ADDRESS);
    OVERLAY("* ! ?CO?USERCOMMONFWUPDATEPASSWORD");
#endif
#if(((_FW_UPDATE_FOREGROUND_SUPPORT == _ON) &&(_FW_UPDATE_CHECK_TYPE != _FW_UPDATE_CHECK_RTK_RSA2048)) || (_FW_UPDATE_BACKGROUND_SUPPORT == _ON))
    BANKX(_DUAL_BANK_USER_FW_CODE_SIZE - 1,"USERCOMMONFWUPDATECRCTABLE");
    TABLE("?CO?USERCOMMONFWUPDATECRCTABLE",0xFFFF);
    OVERLAY("* ! ?CO?USERCOMMONFWUPDATECRCTABLE");
#endif
#endif
}
